export const endpoints = {
  authLogin: '/v1/auth/login',
  authLogout: '/v1/auth/logout',
  authMe: '/v1/auth/me',
  machines: '/v1/machines',
  hierarchy: '/v1/hierarchy',
  morningRounds: '/morning-round',
  morningRoundV2: '/v2/morning-round',
  maintenance: '/maintenance',
  maintenanceLogV2MachineComponents: (machineId: string) =>
    `/v2/maintenance-log/machines/${machineId}/components`,
  maintenanceTasks: '/maintenance-tasks',
  maintenanceTypes: '/v1/maintenance-types',
  treatments: '/v1/treatments',
  forklifts: '/v1/forklifts',
  forkliftReports: '/v1/forklift',
  forkliftReportsOverview: '/v1/reports/forklifts',
  maintenanceTasksReport: '/reports/maintenance-tasks',
  annualPlans: '/v1/annual-plans',
  annualPlansTasks: '/v1/annual-plans/tasks',
  annualPlansTechnicians: '/v1/annual-plans/technicians',
} as const;
